apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: microservices
  labels:
    app: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: 666531394927.dkr.ecr.ap-south-1.amazonaws.com/microservices-cicd-payment:2719deaa43a52491846d19a6af6eadd677213d24
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          envFrom:
            - secretRef:
                name: rds-credentials
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15