apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: microservices
data:
  PAYMENT_SERVICE_URL: "http://payment.microservices.svc.cluster.local"
  NOTIFICATION_SERVICE_URL: "http://notification.microservices.svc.cluster.local"