apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: microservices
  labels:
    app: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: 666531394927.dkr.ecr.ap-south-1.amazonaws.com/microservices-cicd-order:be9fdb27004f1bc9016fca82966d9bd5aff86ff9
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          envFrom:
            - configMapRef:
                name: order-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15