apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-credentials
  namespace: microservices
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: rds-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: microservices-cicd/rds/credentials
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: microservices-cicd/rds/credentials
        property: port
    - secretKey: DB_USER
      remoteRef:
        key: microservices-cicd/rds/credentials
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: microservices-cicd/rds/credentials
        property: password
    - secretKey: DB_NAME
      remoteRef:
        key: microservices-cicd/rds/credentials
        property: dbname